[package]
name = "kraalzibar-server"
version = "0.1.0"
edition = "2024"

[dependencies]
kraalzibar-core = { path = "../kraalzibar-core" }
kraalzibar-storage = { path = "../kraalzibar-storage" }
thiserror = "2"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
