[package]
name = "kraalzibar-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kraalzibar-server"
path = "src/main.rs"

[dependencies]
kraalzibar-core = { path = "../kraalzibar-core" }
kraalzibar-storage = { path = "../kraalzibar-storage" }
prost = "0.13"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tonic = "0.12"

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
tonic = { version = "0.12", features = ["transport"] }

[build-dependencies]
tonic-build = "0.12"
