name: Go SDK CI

on:
  push:
    branches: [main]
    paths:
      - "sdks/go/**"
      - "proto/**"
  pull_request:
    branches: [main]
    paths:
      - "sdks/go/**"
      - "proto/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: "1.22"
          cache-dependency-path: sdks/go/go.sum

      - name: Run tests
        working-directory: sdks/go
        run: go test ./...

      - name: Run vet
        working-directory: sdks/go
        run: go vet ./...
